export const ERROR_TYPES = {

  employee:{
    CREATE_EMPLOYEE:{TAG:"CREATION_ERROR", MESSAGE:"Error inserting new employee, please verify the data!"},
    SEARCH_EMPLOYEE:{TAG:"SEARCH_ERROR", MESSAGE:"This employee was not found!"},
    CPFRG_IN_USE:{TAG:"CPFRG_IN_USE", MESSAGE:"This CPF or RG is already in use!"},
    NOT_FOUND:{TAG:"NOT_FOUND", MESSAGE:"Employee with given ID not found!"}
  },
  database:{
    INSERT_ERROR:{TAG:"INSERT_ERROR", MESSAGE:"ERROR INSERTING DATA INTO DATABASE!"},
    SELECT_ERROR:{TAG:"SELECT_ERROR", MESSAGE:"ERROR SELECTING DATA FROM DATABASE!"},
    DELETE_ERROR:{TAG:"DELETE_ERROR", MESSAGE:"ERROR DELETING DATA FROM DATABASE!"},
    UPDATE_ERROR:{TAG:"UPDATE_ERROR", MESSAGE:"ERROR UPDATING DATA FROM DATABASE!"}
  }
}